import {enableTouchButtons} from './touch-controls.js';
enableTouchButtons();
import {W,H,levels,chapters,createWorld,resetWorld,startWorld,stepWorld,routeComplete,gateOpen} from './physics.js';
import {movableItems,canRotate,canMove,moveItem,rotateItem,setPower,partLabel} from './editor.js';
import {readProgress,saveProgress} from './progress-storage.js';
import {drawObstacles,drawPuzzleGuides} from './puzzle-art.js';
import {drawBumper,drawPortal,drawSwitch,drawGate,drawWire} from './device-art.js';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d');
let world=createWorld(0),selected=0,attempts=1,drag=null,muted=false,audio=null,done=[],last=0,acc=0,resultShown=false;
let saved={done:[],current:0};try{saved=readProgress(localStorage,levels);done=saved.done;}catch{}
const items=()=>movableItems(world);
const rotatable=canRotate;
const effects={bumper:0,portal:0};
function setResolution(){const scale=Math.min(3,Math.max(1,canvas.getBoundingClientRect().width/W*(window.devicePixelRatio||1)));canvas.width=Math.round(W*scale);canvas.height=Math.round(H*scale);ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);}
setResolution();window.addEventListener('resize',()=>{setResolution();draw();});
function sound(freq=300,duration=.1,type='sine',volume=.07){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.65,audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function objectiveUI(){const row=$('#objective-row');row.innerHTML='';for(const [i,id] of world.route.entries()){const chip=document.createElement('span');chip.className='objective-step'+(i<world.routeIndex?' complete':'')+(i===world.routeIndex?' next':'');chip.textContent=(i<world.routeIndex?'✓ ':String(i+1)+'. ')+partLabel(world,id);row.append(chip);if(i<world.route.length-1){const arrow=document.createElement('i');arrow.textContent='←';row.append(arrow);}}const end=document.createElement('span');end.className='objective-goal';end.textContent='יעד';row.append(end);$('#puzzle-rules').textContent=world.rules.join(' · ');}
function controls(){
 const editable=world.mode==='edit',part=items()[selected],power=$('#power');
 document.querySelector('.toolbar').classList.toggle('has-power',items().some(p=>p.powerOptions&&!p.fixed));
 power.hidden=!part?.powerOptions||part.fixed;power.disabled=!editable;
 power.textContent=part?.powerOptions?'עוצמה: '+['עדינה','בינונית','חזקה'][part.powerOptions.indexOf(part.power)]:'';
 const tip=document.querySelector('.interaction-tip');
 tip.textContent=editable&&part?part.label+' — '+(!canMove(part)?canRotate(part)?'גררו את הקצה לסיבוב סביב העוגן':'חלק קבוע; בחרו חלק אחר':!canRotate(part)?part.edit?.move==='x'?'גררו ימינה או שמאלה לאורך הקו':'גררו למעלה או למטה לאורך הקו':part.edit?.move==='x'?'גררו לאורך הקו האופקי; הידית מסובבת':part.edit?.move==='y'?'גררו לאורך הקו האנכי; הידית מסובבת':'גררו להזזה; הידית העגולה מסובבת'):'שחררו, צפו במסלול ותקנו בניסיון הבא';
 $('#release').disabled=world.mode==='running';$('#release').innerHTML=world.mode==='running'?'<span>●</span> השרשרת בתנועה':'<span>▶</span> שחרור הכדור';
 $('#rotate').disabled=!editable||!rotatable(part);$('#status').textContent={edit:'מוכנים לניסוי',running:'תנו לפיזיקה לעבוד',won:'השרשרת הושלמה',failed:'עוד תיקון קטן'}[world.mode];$('#attempt').textContent='ניסיון '+String(attempts).padStart(2,'0');
}
function load(index){
 world=createWorld(index);selected=0;attempts=1;resultShown=false;$('#result').hidden=true;
 $('#level-name').textContent=world.name;$('#current').textContent=String(index+1).padStart(2,'0');$('#level-tag').textContent=String(index+1).padStart(2,'0')+' — '+world.name;
 $('#description').textContent=world.description;$('#hint').textContent=world.hint;$('#hint').hidden=true;$('#chapter-name').textContent=String(world.chapter+1).padStart(2,'0')+' / '+chapters[world.chapter].name;
 $('#prev-chapter').disabled=world.chapter===0;$('#next-chapter').disabled=world.chapter===chapters.length-1;
 try{saveProgress(localStorage,levels,done,index);}catch{}
 $('#levels').querySelectorAll('.level-button').forEach((b,i)=>{b.style.display=levels[i].chapter===world.chapter?'':'none';b.classList.toggle('active',index===i);b.setAttribute('aria-current',index===i?'step':'false');b.classList.toggle('done',done.includes(i));});
 $('#completed').textContent=done.length+' / '+levels.length+' הושלמו';
 if(innerWidth<=800){requestAnimationFrame(()=>{const active=$('#levels .active');if(active)$('#levels').scrollLeft=active.offsetLeft-$('#levels').offsetLeft-$('#levels').clientWidth/2+22;});}
 objectiveUI();controls();draw();
}
levels.forEach((l,i)=>{const b=document.createElement('button');b.className='level-button';b.textContent=String(i+1).padStart(2,'0');b.title=l.name;b.setAttribute('aria-label','שלב '+(i+1)+': '+l.name);b.onclick=()=>load(i);$('#levels').append(b);});
function mapLevels(){const map=$('#chapter-map');map.innerHTML='';chapters.forEach((c,chapter)=>{const s=document.createElement('section');s.className='map-chapter';const h=document.createElement('h3');h.textContent=String(chapter+1).padStart(2,'0')+' / '+c.name;const small=document.createElement('small');small.textContent=c.mechanic;h.append(small);s.append(h);const row=document.createElement('div');row.className='map-row';for(let n=0;n<c.count;n++){const i=c.start+n,b=document.createElement('button');b.className='level-button'+(done.includes(i)?' done':'')+(world.index===i?' active':'');b.textContent=String(i+1).padStart(2,'0');b.setAttribute('aria-label','שלב '+(i+1)+': '+levels[i].name);b.onclick=()=>{load(i);$('#levels-dialog').close();};row.append(b);}s.append(row);map.append(s);});}
$('#open-levels').onclick=()=>{mapLevels();$('#levels-dialog').showModal();};$('#close-levels').onclick=()=>$('#levels-dialog').close();$('#prev-chapter').onclick=()=>load(chapters[Math.max(0,world.chapter-1)].start);$('#next-chapter').onclick=()=>load(chapters[Math.min(chapters.length-1,world.chapter+1)].start);$('#show-hint').onclick=()=>{$('#hint').hidden=!$('#hint').hidden;};
function retry(){attempts++;resetWorld(world);objectiveUI();resultShown=false;$('#result').hidden=true;controls();draw();}
function release(){if(world.mode==='running')return;if(world.mode!=='edit')retry();sound(550,.08);startWorld(world);controls();canvas.focus({preventScroll:true});}
$('#power').onclick=()=>{const p=items()[selected];if(world.mode==='edit'&&p?.powerOptions){setPower(p,p.powerOptions[(p.powerOptions.indexOf(p.power)+1)%p.powerOptions.length]);controls();draw();sound(650,.035);}};
$('#release').onclick=release;$('#retry').onclick=retry;$('#rotate').onclick=()=>{const r=items()[selected];if(rotatable(r)&&world.mode==='edit'){rotateItem(r,r.a+Math.PI/12,world);sound(600,.025);draw();}};$('#reset-layout').onclick=()=>load(world.index);
$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'♫̸':'♪';$('#sound').setAttribute('aria-label',muted?'הפעלת צלילים':'השתקת צלילים');$('#sound').setAttribute('aria-pressed',String(muted));if(!muted)sound();};
$('#help').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=$('#got-it').onclick=()=>$('#help-dialog').close();$('#help-dialog').addEventListener('click',e=>{if(e.target===$('#help-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#result-retry').onclick=retry;$('#result-action').onclick=()=>world.mode==='won'?load((world.index+1)%levels.length):retry();
function result(){if(resultShown)return;resultShown=true;const won=world.mode==='won';if(won&&!done.includes(world.index)){done.push(world.index);try{saveProgress(localStorage,levels,done,world.index);}catch{}document.querySelectorAll('.level-button')[world.index].classList.add('done');$('#completed').textContent=done.length+' / '+levels.length+' הושלמו';}$('#result').hidden=false;$('#result').classList.toggle('failed',!won);$('#result-icon').textContent=won?'✓':'↗';$('#result-label').textContent=won?'הכול התחבר':'עוד קצת, וזה שם';$('#result-title').textContent=won?(world.index===levels.length-1?'תגובת שרשרת מושלמת.':'איזו שרשרת.'):'כמעט.';$('#result-description').textContent=won?`${world.contacts} פגיעות · ${world.time.toFixed(1)} שניות · ${attempts===1?'בניסיון הראשון':'בניסיון '+attempts}`:(world.failure||world.hint);$('#result-action').textContent=won?(world.index===levels.length-1?'בחזרה להתחלה ↻':'לשלב הבא ←'):'תיקון קטן וניסיון נוסף ↻';$('#result-retry').hidden=!won;controls();if(won){[440,554,659,880].forEach((f,i)=>setTimeout(()=>sound(f,.25,'sine',.05),i*90));if(navigator.vibrate)navigator.vibrate([20,35,20]);}else sound(180,.15);}
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function screw(x,y,size=6){ctx.save();ctx.translate(x,y);ctx.shadowColor='#4a453a66';ctx.shadowBlur=3;ctx.shadowOffsetY=2;const g=ctx.createLinearGradient(-size,-size,size,size);g.addColorStop(0,'#fffff8');g.addColorStop(.45,'#a9a79a');g.addColorStop(.7,'#e1ded2');g.addColorStop(1,'#6e6d62');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,size,0,7);ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle='#6d6b60';ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(-size*.55,-size*.55);ctx.lineTo(size*.55,size*.55);ctx.moveTo(size*.55,-size*.55);ctx.lineTo(-size*.55,size*.55);ctx.stroke();ctx.restore();}
function rail(r,i){ctx.save();ctx.translate(r.x,r.y);ctx.rotate(r.a);ctx.shadowColor='#594c3745';ctx.shadowBlur=13;ctx.shadowOffsetX=6;ctx.shadowOffsetY=12;const g=ctx.createLinearGradient(0,-10,0,20);g.addColorStop(0,'#fffdf4');g.addColorStop(.55,'#e4decf');g.addColorStop(1,'#b9b1a1');rounded(-r.len/2,-3,r.len,23,4,g,'#c3bbab');ctx.shadowBlur=0;ctx.shadowOffsetX=0;ctx.shadowOffsetY=0;rounded(-r.len/2,-8,r.len,8,3,'#e56850');rounded(-r.len/2,-8,r.len,3,2,'#ffad94');screw(-r.len/2+14,8,5);screw(r.len/2-14,8,5);if(world.mode==='edit'&&rotatable(r)){ctx.strokeStyle='#d5a895';ctx.setLineDash([3,5]);ctx.strokeRect(-r.len/2-7,-15,r.len+14,42);ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(r.len/2+8,4);ctx.lineTo(r.len/2+28,4);ctx.stroke();ctx.fillStyle='#f8f5ec';ctx.beginPath();ctx.arc(r.len/2+35,4,11,0,7);ctx.fill();ctx.strokeStyle='#d39073';ctx.stroke();ctx.fillStyle='#b47c63';ctx.font='16px Arial';ctx.textAlign='center';ctx.fillText('⟳',r.len/2+35,9);}ctx.restore();}
function spring(s,i){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);ctx.shadowColor='#4c4b3550';ctx.shadowOffsetY=7;ctx.shadowBlur=10;rounded(-26,-25,45,50,9,'#c9bba0','#b4a386');ctx.shadowBlur=0;ctx.shadowOffsetY=0;rounded(12,-28,9,56,4,'#e99b58');ctx.strokeStyle='#f9f5e5';ctx.lineWidth=4;ctx.beginPath();for(let x=-20;x<=9;x+=5)ctx.lineTo(x,(x/5%2)?12:-12);ctx.stroke();ctx.strokeStyle='#827868';ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle='#c7793f';ctx.beginPath();ctx.moveTo(43,0);ctx.lineTo(31,-6);ctx.lineTo(31,6);ctx.fill();if(selected===i&&world.mode==='edit'&&rotatable(s)){ctx.strokeStyle='#d39073';ctx.setLineDash([3,4]);ctx.strokeRect(-33,-33,62,66);ctx.setLineDash([]);ctx.beginPath();ctx.arc(57,0,11,0,7);ctx.fillStyle='#f8f5ec';ctx.fill();ctx.stroke();ctx.font='16px Arial';ctx.textAlign='center';ctx.fillStyle='#b47c63';ctx.fillText('⟳',57,5);}ctx.restore();}
function domino(d){ctx.save();ctx.translate(d.x,d.y);ctx.rotate(d.angle*(d.dir||1));ctx.scale(1,(d.height||80)/80);ctx.shadowColor='#4b4c3548';ctx.shadowBlur=8;ctx.shadowOffsetX=7;ctx.shadowOffsetY=6;const g=ctx.createLinearGradient(-9,0,12,0);g.addColorStop(0,'#78a6a6');g.addColorStop(.25,'#47888c');g.addColorStop(.8,'#377077');g.addColorStop(1,'#255962');rounded(-9,-80,18,80,3,g,'#326a6c');ctx.shadowBlur=0;ctx.shadowOffsetX=0;ctx.shadowOffsetY=0;rounded(-8,-80,16,5,2,'#9dbebb');ctx.strokeStyle='#3d7274';ctx.beginPath();ctx.moveTo(-5,-38);ctx.lineTo(5,-38);ctx.stroke();ctx.restore();}
function ball(b){ctx.save();ctx.translate(b.x,b.y);ctx.shadowColor='#554e4055';ctx.shadowBlur=9;ctx.shadowOffsetX=4;ctx.shadowOffsetY=9;const g=ctx.createRadialGradient(-5,-7,1,1,2,15);g.addColorStop(0,'#ffffff');g.addColorStop(.17,'#e6e8e4');g.addColorStop(.32,'#868d88');g.addColorStop(.49,'#303834');g.addColorStop(.72,'#959992');g.addColorStop(.86,'#f1eee2');g.addColorStop(1,'#535b55');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,b.r,0,7);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#a4a79b';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#ffffffb0';ctx.beginPath();ctx.ellipse(-4,-6,4,3,-.6,0,7);ctx.fill();ctx.restore();}
function target(){const {x,y}=world.goal;ctx.save();ctx.translate(x,y);ctx.shadowColor='#95634245';ctx.shadowBlur=8;ctx.shadowOffsetY=6;const g=ctx.createLinearGradient(-30,-30,30,30);g.addColorStop(0,'#ffbaa1');g.addColorStop(.4,'#ee785f');g.addColorStop(1,'#d65b47');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,30,0,7);ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle='#ffbc9f';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle='#be4f3e';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,21,0,7);ctx.stroke();ctx.fillStyle='#ee7b62';ctx.beginPath();ctx.arc(0,1,18,0,7);ctx.fill();ctx.strokeStyle='#f7997c';ctx.lineWidth=1;ctx.stroke();if(!routeComplete(world)||!gateOpen(world)){ctx.fillStyle='#90594b';rounded(-6,-4,12,12,2,'#90594b');ctx.strokeStyle='#90594b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-4,4,Math.PI,0);ctx.stroke();}ctx.restore();}
function extras(){const state={selected,mode:world.mode,switchOn:gateOpen(world),effects};let i=world.rails.length+world.springs.length;if(world.gate){for(const s of world.switches)drawWire(ctx,s,world.gate,world.switchStates[s.id]!==undefined);drawGate(ctx,world.gate,state);}for(const d of world.bumpers||[])drawBumper(ctx,d,i++,state);for(const [n,d] of (world.portals||[]).entries())drawPortal(ctx,d,n,i++,state);for(const s of world.switches)drawSwitch(ctx,s,i++,{...state,switchOn:world.switchStates[s.id]!==undefined});}
function renderMechanicPreviews(){for(const [selector,render] of [['.mini-extra:not(.mini-portal):not(.mini-switch)',(c)=>drawBumper(c,{x:0,y:0,a:-.6},-1,{})],['.mini-portal',(c)=>drawPortal(c,{x:0,y:0},0,-1,{})],['.mini-switch',(c)=>drawSwitch(c,{x:0,y:0},-1,{switchOn:false})]]){const host=$(selector);if(!host)continue;host.textContent='';const preview=document.createElement('canvas');preview.width=128;preview.height=128;const c=preview.getContext('2d');c.translate(64,57);c.scale(1.35,1.35);render(c);const img=new Image();img.alt='';img.src=preview.toDataURL();host.append(img);}}
renderMechanicPreviews();
function draw(){ctx.clearRect(0,0,W,H);const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,'#f2ede2');bg.addColorStop(.5,'#e9e3d7');bg.addColorStop(1,'#e1d9cb');rounded(0,0,W,H,23,bg);ctx.save();ctx.shadowColor='#75664b55';ctx.shadowBlur=7;ctx.shadowOffsetY=3;rounded(11,11,W-22,H-22,19,null,'#c4b9a6');ctx.restore();ctx.strokeStyle='#fffdf5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(35,12);ctx.lineTo(W-35,12);ctx.stroke();for(let y=48;y<H-35;y+=43)for(let x=47;x<W-30;x+=43){ctx.fillStyle='#fff9ed';ctx.beginPath();ctx.arc(x+.5,y+1,2.6,0,7);ctx.fill();ctx.fillStyle='#b1a796';ctx.beginPath();ctx.arc(x,y,2.3,0,7);ctx.fill();}[[28,28],[W-28,28],[28,H-28],[W-28,H-28]].forEach(p=>screw(...p,8));
 drawObstacles(ctx,world);target();extras();if(world.trail.length>2){ctx.beginPath();world.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle='#c87a5940';ctx.lineWidth=2;ctx.setLineDash([2,7]);ctx.stroke();ctx.setLineDash([]);}world.rails.forEach(rail);world.springs.forEach((s,i)=>spring(s,world.rails.length+i));world.dominoes.forEach(domino);if(world.mode==='edit'){ctx.fillStyle='#8c8779';ctx.textAlign='center';ctx.font='10px Arial';ctx.fillText('START',world.ball.x,world.ball.y-28);ctx.setLineDash([2,5]);ctx.strokeStyle='#b5ac9850';ctx.beginPath();ctx.moveTo(world.ball.x,world.ball.y+25);ctx.lineTo(world.ball.x,world.ball.y+65);ctx.stroke();ctx.setLineDash([]);}drawPuzzleGuides(ctx,world,selected);ball(world.ball);for(const p of world.particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();}ctx.globalAlpha=1;}
function update(dt){effects.bumper=Math.max(0,effects.bumper-dt*5);effects.portal=Math.max(0,effects.portal-dt*3);stepWorld(world,dt);for(const e of world.events.splice(0)){if(e.type==='checkpoint')objectiveUI();if(e.type==='hit')sound(180+Math.min(e.energy,500),.055,'sine',.035);if(e.type==='domino')sound(280+world.contacts*70,.075,'triangle',.04);if(e.type==='bumper')effects.bumper=1;if(e.type==='portal')effects.portal=1;if(e.type==='portal')sound(850,.2,'sine',.045);if(e.type==='switch')sound(1050,.12,'triangle',.04);if(e.type==='bumper')sound(350,.15,'triangle',.05);if(e.type==='spring')sound(650,.18,'triangle',.05);if(e.x!==undefined)for(let i=0;i<7;i++)world.particles.push({x:e.x,y:e.y,vx:Math.cos(i)*45,vy:Math.sin(i)*45-25,life:.6,r:2,color:e.type==='domino'?'#4f9496':'#ed9973'});if(e.type==='won'||e.type==='failed')result();}for(const p of world.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt;p.life-=dt;}world.particles=world.particles.filter(p=>p.life>0);}
function frame(t){const elapsed=Math.min(.05,(t-last)/1000||0);last=t;const active=world.mode==='running'||world.particles.length>0||effects.bumper>0||effects.portal>0;if(active){acc+=elapsed;while(acc>=1/120){update(1/120);acc-=1/120;}draw();}else acc=0;requestAnimationFrame(frame);}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};}
canvas.addEventListener('pointerdown',e=>{
 if(world.mode!=='edit')return;
 const p=point(e),all=items(),scale=W/canvas.getBoundingClientRect().width,hits=[];
 for(const [i,r] of all.entries()){
  const angle=r.a||0,len=r.len||44,dx=p.x-r.x,dy=p.y-r.y;
  const lx=dx*Math.cos(angle)+dy*Math.sin(angle),ly=-dx*Math.sin(angle)+dy*Math.cos(angle);
  const hx=r.len?len/2+35:57,hy=r.len?4:0,handleDistance=Math.hypot(lx-hx,ly-hy);
  if(rotatable(r)&&handleDistance<Math.max(20,24*scale))hits.push({i,rotate:true,distance:handleDistance});
  if(Math.abs(lx)<(r.len?len/2+12:Math.max(39,22*scale))&&Math.abs(ly)<Math.max(r.len?25:34,22*scale))hits.push({i,rotate:false,distance:r.len?Math.hypot(Math.max(0,Math.abs(lx)-len/2),ly):Math.hypot(dx,dy)});
 }
 hits.sort((a,b)=>a.distance-b.distance||Number(b.rotate)-Number(a.rotate));
 const hit=hits[0];if(!hit)return;
 selected=hit.i;const r=all[selected],angle=r.a||0,dx=p.x-r.x,dy=p.y-r.y;controls();
 if(!canMove(r)&&!canRotate(r)){$('#status').textContent='חלק קבוע — אי אפשר להזיז';draw();e.preventDefault();return;}
 drag={id:e.pointerId,rotate:hit.rotate||(!canMove(r)&&canRotate(r)),center:!hit.rotate&&!canMove(r)&&Math.hypot(dx,dy)<20,startX:p.x,startAngle:angle,dx,dy,offset:Math.atan2(dy,dx)-angle};
 canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});draw();e.preventDefault();
});
canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const p=point(e),r=items()[selected];if(drag.rotate)rotateItem(r,drag.center?drag.startAngle+(p.x-drag.startX)*.01:Math.atan2(p.y-r.y,p.x-r.x)-drag.offset,world);else moveItem(r,p.x-drag.dx,p.y-drag.dy,world);draw();});
function endDrag(){if(drag)sound(440,.025);drag=null;}canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);
window.addEventListener('keydown',e=>{if($('#help-dialog').open||$('#levels-dialog').open)return;if(e.target.matches('button')&&['Enter',' '].includes(e.key))return;const r=items()[selected];if(e.key===' '){e.preventDefault();release();}if(e.key.toLowerCase()==='r')retry();if(e.key.toLowerCase()==='f'){if(document.fullscreenElement)document.exitFullscreen();else canvas.requestFullscreen?.();}if(world.mode!=='edit'||!r)return;if(e.key==='Tab'&&e.target===canvas){if(selected<items().length-1){e.preventDefault();selected++;}else selected=0;}if(e.key.startsWith('Arrow')){e.preventDefault();moveItem(r,r.x+(e.key==='ArrowRight'?10:e.key==='ArrowLeft'?-10:0),r.y+(e.key==='ArrowDown'?10:e.key==='ArrowUp'?-10:0),world);}if(rotatable(r)&&e.key.toLowerCase()==='a')rotateItem(r,r.a-Math.PI/36,world);if(rotatable(r)&&e.key.toLowerCase()==='d')rotateItem(r,r.a+Math.PI/36,world);controls();draw();});
window.render_game_to_text=()=>JSON.stringify({coordinates:'origin top-left, +x right, +y down; logical board 700x630',level:world.index+1,name:world.name,mode:world.mode,attempts,time:+world.time.toFixed(2),selected,ball:world.ball,rails:world.rails,spring:world.spring||null,springs:world.springs,bumpers:world.bumpers||[],portals:world.portals||[],switch:world.switch||null,switches:world.switches,switchStates:world.switchStates,switchOn:world.switchOn,gate:world.gate||null,dominoes:world.dominoes,goal:world.goal,contacts:world.contacts,completed:done,route:world.route,routeIndex:world.routeIndex,rules:world.rules,walls:world.walls,hazards:world.hazards,failure:world.failure,gateOpen:gateOpen(world)});
window.advanceTime=ms=>{for(let i=0;i<Math.ceil(ms/(1000/120));i++)update(1/120);draw();};
load(saved.current);requestAnimationFrame(frame);

if(!new URLSearchParams(location.search).has('native')&&'serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
