import {canMove,canRotate,movableItems} from './editor.js';
import {portalPairsOf} from './parts.js';
function box(c,x,y,w,h,fill,stroke){c.beginPath();c.roundRect(x,y,w,h,4);c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=1;c.stroke();}}
export function drawObstacles(c,w){
 for(const r of w.walls||[]){c.save();c.shadowColor='#443c3155';c.shadowBlur=6;c.shadowOffsetX=3;c.shadowOffsetY=5;const g=c.createLinearGradient(r.x,r.y,r.x+r.w,r.y+r.h);g.addColorStop(0,'#c6ccc1');g.addColorStop(.35,'#9fa99f');g.addColorStop(1,'#697a70');box(c,r.x,r.y,r.w,r.h,g,'#919e90');c.shadowBlur=0;c.shadowOffsetX=0;c.shadowOffsetY=0;c.strokeStyle='#e6ebdba0';c.beginPath();c.moveTo(r.x+2,r.y+3);c.lineTo(r.x+2,r.y+r.h-3);c.stroke();for(const y of [r.y+9,r.y+r.h-9]){c.fillStyle='#5d6e62';c.beginPath();c.arc(r.x+r.w/2,y,2.7,0,7);c.fill();c.strokeStyle='#c7cbb9';c.lineWidth=.8;c.beginPath();c.moveTo(r.x+r.w/2-1.5,y-1);c.lineTo(r.x+r.w/2+1.5,y+1);c.stroke();}c.restore();}
 for(const r of w.hazards||[]){c.save();c.shadowColor='#66533d50';c.shadowBlur=5;c.shadowOffsetY=3;box(c,r.x-3,r.y-3,r.w+6,r.h+6,'#b8a99a','#d5cbb9');c.shadowBlur=0;c.shadowOffsetY=0;box(c,r.x,r.y,r.w,r.h,'#4e4940');c.save();c.beginPath();c.rect(r.x,r.y,r.w,r.h);c.clip();c.strokeStyle='#d48f6b';c.lineWidth=5;for(let x=r.x-r.h;x<r.x+r.w;x+=15){c.beginPath();c.moveTo(x,r.y+r.h);c.lineTo(x+r.h,r.y);c.stroke();}c.restore();c.restore();}
}
function tag(c,p,text,complete){const x=p.x,y=p.y-(p.len?25:p.id==='switch'?46:48);c.save();c.fillStyle=complete?'#5d8979':'#958773';c.beginPath();c.arc(x,y,8,0,7);c.fill();c.fillStyle='#faf7ee';c.font='9px Arial';c.textAlign='center';c.fillText(complete?'✓':text,x,y+3);c.restore();}
export function drawPuzzleGuides(c,w,selected){const all=movableItems(w),r=all[selected];
 if(w.mode==='edit'&&r){const e=r.edit;if(canMove(r)&&e?.bounds){const b=e.bounds;c.save();c.strokeStyle='#829e9b70';c.lineWidth=1.2;c.setLineDash([3,6]);if(e.move==='x'||e.move==='y'){c.beginPath();c.moveTo(e.move==='x'?b.xMin:r.x,e.move==='y'?b.yMin:r.y);c.lineTo(e.move==='x'?b.xMax:r.x,e.move==='y'?b.yMax:r.y);c.stroke();c.setLineDash([]);for(const p of [{x:e.move==='x'?b.xMin:r.x,y:e.move==='y'?b.yMin:r.y},{x:e.move==='x'?b.xMax:r.x,y:e.move==='y'?b.yMax:r.y}]){c.beginPath();c.arc(p.x,p.y,3,0,7);c.stroke();}}else {c.strokeRect(b.xMin,b.yMin,b.xMax-b.xMin,b.yMax-b.yMin);}c.restore();}}
 for(const p of all){const order=(w.route||[]).indexOf(p.id);if(order>=0)tag(c,p,String(order+1),order<w.routeIndex);if(w.mode==='edit'&&!canMove(p)&&canRotate(p)){c.save();c.translate(p.x,p.y);c.fillStyle='#f8f5ec';c.strokeStyle='#b47c63';c.lineWidth=2;c.beginPath();c.arc(0,0,9,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#82705d';c.beginPath();c.arc(0,0,3,0,Math.PI*2);c.fill();c.restore();}if(p.fixed){c.save();c.fillStyle='#807d7050';box(c,p.x-5,p.y+34,10,8,'#797d70');c.strokeStyle='#797d70';c.lineWidth=1.2;c.beginPath();c.arc(p.x,p.y+34,3,Math.PI,0);c.stroke();c.restore();}}
 for(const pair of portalPairsOf(w)){const index=w.route.indexOf(pair.id);if(index>=0)tag(c,pair.entrance,String(index+1),index<w.routeIndex);}
 if(w.dominoes.length){const index=w.route.indexOf('domino');if(index>=0)tag(c,{x:w.dominoes[0].x,y:w.dominoes[0].y-55},String(index+1),index<w.routeIndex);}
}
