import assert from 'node:assert/strict';
import {createPlayerStore} from '../player-storage.js';
const values=new Map(),storage={getItem:key=>values.get(key),setItem:(key,value)=>values.set(key,value)};
const levels=[{id:'one'},{id:'two'}],legacy={completed:['one'],current:'two'};
const store=createPlayerStore(storage);
store.add('  דני  ',legacy);const first=store.active().id;
assert.deepEqual(store.progress(levels,{}),{done:[0],current:1});
assert.throws(()=>store.add('דני',legacy));assert.throws(()=>store.add('<script>',legacy));
assert.ok(store.record('one',2,4));assert.ok(!store.record('one',3,1));assert.ok(store.record('one',2,3));
store.add('נועה',legacy);assert.deepEqual(store.progress(levels,{}),{done:[],current:0});
store.save(levels,[0],0);store.record('one',1,5);
assert.equal(store.leaderboard(levels,'one')[0].name,'נועה');
store.select(first);assert.equal(store.active().records.one.time,3);
assert.equal(createPlayerStore(storage).active().name,'דני');
store.select(null);assert.equal(store.record('two',1,2),false);
assert.equal(store.leaderboard(levels,'two').length,0);
assert.equal(createPlayerStore({getItem:()=>'{broken',setItem:()=>{}}).players().length,0);
const blocked=createPlayerStore({getItem:()=>null,setItem:()=>{throw new Error('quota');}});
assert.throws(()=>blocked.add('דני',legacy));assert.equal(blocked.players().length,0);
console.log('Player storage: migration, isolation, ranking, best scores, reload, validation and storage failures passed.');
